# Merged Brewfile
# Organized by category for readability and maintenance (alphabetized where appropriate).
# Generated by merge script: union of `Brewfile` + `Brewfile.bak`
# NOTE: `ffmpeg@4` removed in favor of the non-pinned `ffmpeg` (use latest).

# -------------------------
# Taps
# -------------------------
# Additional taps from backups
tap "charmbracelet/tap"
tap "facebook/fb"
tap "modularml/packages"
tap "supabase/tap"

# -------------------------
# System & CLI utilities
# (coreutils, shells, search, navigation, misc)
# -------------------------
brew "bat"
brew "coreutils" # GNU core utilities
brew "curl"
brew "eza" # Modern ls replacement (successor to exa)
brew "fd"
brew "fzf"
brew "git"
brew "htop"
brew "hyperfine"
brew "just"
brew "jq"
brew "ripgrep"
brew "shellcheck" # Static analysis tool for shell scripts
brew "tldr" # Better man pages
brew "tree"
brew "trash" # Safe rm replacement
brew "watchexec"
brew "wget"
brew "zoxide" # Better cd
brew "zsh"

# -------------------------
# Development toolchain
# (languages, build tools, CLIs)
# -------------------------
brew "composer"
brew "cocoapods"
brew "go"
brew "go-air"
brew "delve"
brew "gopls"
brew "mise"
brew "node"
brew "php"
brew "python@3.12"
brew "rbenv" # Ruby version manager
brew "rust"
brew "uv" # Python package and project manager
brew "direnv"

# -------------------------
# Containers & infra
# -------------------------
brew "awscli"
brew "docker"
brew "kubectl"
brew "minikube" # Local Kubernetes
brew "terraform"

# -------------------------
# Networking, servers & infra tools
# -------------------------
brew "caddy"
brew "cloudflared"

# -------------------------
# Multimedia & general utilities
# -------------------------
brew "bfg"
brew "ffmpeg" # use latest
brew "imagemagick" # Image processing
brew "ios-deploy"
brew "mole"
brew "qrencode" # QR code generator
brew "xz"
brew "yt-dlp"

# -------------------------
# Databases & GIS
# -------------------------
brew "postgis"
brew "postgresql@15"
brew "sqlite"

# -------------------------
# Git & productivity helpers
# -------------------------
brew "gh" # GitHub CLI
brew "git-delta" # Better git diff

# -------------------------
# Other CLI utilities
# -------------------------
brew "block-goose-cli"
cask "codex"
brew "huggingface-cli"
brew "opencode"

# -------------------------
# Fonts (single canonical coding font)
# -------------------------
cask "font-geist-mono-nerd-font"

# -------------------------
# GUI applications (casks)
# -------------------------
cask "1password" # Password manager
cask "discord" # Community
cask "figma" # Design tool
cask "ghostty"
cask "google-chrome" # Web browser
cask "obsidian" # Note taking
cask "postman" # API development
cask "setapp" # App store
cask "slack" # Team communication
cask "spotify" # Music streaming
cask "visual-studio-code" # Code editor

# -------------------------
# Utilities (GUI)
# -------------------------
cask "bartender"
cask "raycast"
cask "rectangle" # Window management
cask "the-unarchiver"

# -------------------------
# Development utilities (GUI)
# -------------------------
cask "proxyman" # HTTP debugging

# -------------------------
# VS Code extensions (keep grouped for easy review; alphabetized)
# -------------------------
vscode "1yib.rust-bundle"
vscode "aaron-bond.better-comments"
vscode "astro-build.astro-vscode"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bradlc.vscode-tailwindcss"
vscode "charliermarsh.ruff"
vscode "clinyong.vscode-css-modules"
vscode "docker.docker"
vscode "dustypomerleau.rust-syntax"
vscode "eamodio.gitlens"
vscode "expo.vscode-expo-tools"
vscode "figma.figma-vscode-extension"
vscode "foam.foam-vscode"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "lokalise.i18n-ally"
vscode "mechatroner.rainbow-csv"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-ossdata.vscode-pgsql"
vscode "ms-playwright.playwright"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "msjsdiag.vscode-react-native"
vscode "mushan.vscode-paste-image"
vscode "oven.bun-vscode"
vscode "oxc.oxc-vscode"
vscode "pomdtr.excalidraw-editor"
vscode "prisma.prisma"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "streetsidesoftware.code-spell-checker"
vscode "svelte.svelte-vscode"
vscode "swiftlang.swift-vscode"
vscode "takumii.markdowntable"
vscode "tamasfe.even-better-toml"
vscode "teabyii.ayu"
vscode "twxs.cmake"
vscode "unifiedjs.vscode-mdx"
vscode "upstash.context7-mcp"
vscode "vitest.explorer"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "zamerick.vscode-caddyfile-syntax"
