# ======================================================================
# PERFORMANCE OPTIMIZATIONS
# ======================================================================
# Enable profiling (comment out after profiling)
# zmodload zsh/zprof

# Disable compinit security checks for faster startup
ZSH_DISABLE_COMPFIX=true
# Suppress instant prompt warnings for background processes and console output
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Redirect all potential output during initialization to prevent instant prompt issues
exec 3>&1 4>&2 >/dev/null 2>&1
# Skip global compinit for faster startup
skip_global_compinit=1

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

# Restore stdout and stderr after instant prompt is loaded
exec 1>&3 2>&4 3>&- 4>&-

# (Reverted) compinit tweaks removed — using default compinit behavior
# ======================================================================
# ANTIBODY SETUP
# ======================================================================
# Plugin management moved to antibody; bundle is generated during installation and sourced later.
# See home/antibody-plugins.txt and install.sh for bundle generation.

# ======================================================================
# CORE SYSTEM CONFIGURATION
# ======================================================================
SYSTEM_PATH=~/.dotfiles/system

# Load environment, settings, aliases, and functions
source $SYSTEM_PATH/env.zsh 2>/dev/null
source $SYSTEM_PATH/settings.zsh 2>/dev/null
source $SYSTEM_PATH/aliases.zsh 2>/dev/null
source $SYSTEM_PATH/functions.zsh 2>/dev/null

# Load dotfiles library for shell usage
source $HOME/.dotfiles/bin/lib.sh 2>/dev/null

# ======================================================================
# DEVELOPMENT TOOLS SETUP
# ======================================================================
if [[ -z "${MISE_ACTIVATED:-}" ]]; then
    eval "$(mise activate zsh --shims)"
    export MISE_ACTIVATED=1
fi

# ======================================================================
# PLUGINS AND THEMES
# ======================================================================
# Load plugin bundle generated by antibody; bundle is precompiled at install time for fast startup.
ANTIBODY_BUNDLE="${HOME}/.local/share/antibody/bundle.zsh"
if [[ -f "${ANTIBODY_BUNDLE}" ]]; then
  autoload -Uz add-zsh-hook 2>/dev/null
  function __defer_antibody_bundle() {
    source "${ANTIBODY_BUNDLE}" 2>/dev/null || true
    add-zsh-hook -d precmd __defer_antibody_bundle 2>/dev/null || true
    unfunction __defer_antibody_bundle
  }
  add-zsh-hook precmd __defer_antibody_bundle
fi

# Powerlevel10k removed in favor of Starship (Starship is initialized below if installed)
# If you later want to restore Powerlevel10k, uncomment the lines below.
# zinit ice depth"1"
# zinit light romkatv/powerlevel10k
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Optionally enable Starship prompt if installed. Starship is a fast, cross-shell
# prompt written in Rust. Uncomment to prefer Starship over Powerlevel10k.
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init zsh)"
fi

# Initialize zoxide (better cd)
if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init zsh)"
fi

# ======================================================================
# TOOL CONFIGURATIONS
# ======================================================================
# Lazy load fzf key bindings - only when needed, suppress output
[ -f ~/.fzf.zsh ] && {
    fzf() {
        source ~/.fzf.zsh 2>/dev/null
        unfunction fzf
        fzf "$@"
    }
}

# ======================================================================
# APPLICATION SPECIFIC SETTINGS
# ======================================================================
# Set default shell for VSCode - suppress any output
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)" 2>/dev/null

# ======================================================================
# LOCAL CONFIGURATION
# ======================================================================
# Load local computer specific configuration if it exists - suppress output
[ -f ~/.localrc ] && source ~/.localrc 2>/dev/null

# Homebrew
if ! grep -qxF 'eval "$(/opt/homebrew/bin/brew shellenv)"' ~/.zprofile 2>/dev/null; then
    printf '\n' >> ~/.zprofile
    printf '%s\n' 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
fi
eval "$(/opt/homebrew/bin/brew shellenv)"

. "$HOME/.turso/env"

# ======================================================================
# COMPLETION CONFIGURATION (Added by Gemini)
# ======================================================================
# 1. Dedicated site-functions directory for completions (consolidate sources to speed compinit)
ZSH_SITE_FUNCS="${HOME}/.local/share/zsh/site-functions"
mkdir -p "$ZSH_SITE_FUNCS"

# Prefer Homebrew completion directories (both legacy locations)
if type brew &>/dev/null; then
  BREW_PREFIX="$(brew --prefix)"
  for BREW_COMP_DIR in "$BREW_PREFIX/share/zsh/site-functions" "$BREW_PREFIX/share/zsh-completions"; do
    if [[ -d "$BREW_COMP_DIR" ]]; then
      if command -v rsync >/dev/null 2>&1; then
        rsync -a --ignore-existing "$BREW_COMP_DIR/" "$ZSH_SITE_FUNCS/" 2>/dev/null || true
      else
        for f in "$BREW_COMP_DIR"/*; do
          [[ -f "$f" && ! -e "$ZSH_SITE_FUNCS/$(basename "$f")" ]] && cp -n "$f" "$ZSH_SITE_FUNCS/"
        done
      fi
    fi
  done
fi

# Ensure site-functions is first in FPATH (deduplicated)
if [[ ":$FPATH:" != *":$ZSH_SITE_FUNCS:"* ]]; then
  FPATH="$ZSH_SITE_FUNCS:$FPATH"
fi

# 2. Initialize completion system (explicitly required if skipped above)
autoload -Uz compinit
# Use cached compdump when present; rebuild only if missing
if [[ -f ~/.zcompdump ]]; then
  compinit -C
else
  compinit
fi

# 3. Case-Insensitive Completion (Key feature request)
# Matches: a -> A, a -> a
zstyle ":completion:*" matcher-list "m:{a-zA-Z}={A-Za-z}" "r:|[._-]=* r:|=*" "l:|=* r:|=*"

# 4. Usability Enhancements
# Use a selection menu when multiple options are available
zstyle ":completion:*" menu select
# Group completions by category (e.g., Aliases, Commands, Files)
zstyle ":completion:*" group-name ""
# Colored completion lists
zstyle ":completion:*" list-colors ""
# Complete . and .. special directories
zstyle ":completion:*" special-dirs true
