version: "2"

services:
    postgres:
        image: postgres
        restart: always
        container_name: ponti-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - ${HOME}/.docker/volumes/postgres:/var/lib/postgresql/data
        env_file:
            - ./.env

    rabbitmq:
        image: rabbitmq:3-management
        container_name: ponti-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        env_file:
            - ./.env

volumes:
    postgres_data:
    rabbitmq_data:
