set shell := ["/usr/bin/env", "bash", "-lc"]

default:
    @just --list

test:
    npm test

lint:
    npm run lint && npm run typecheck

watch-test:
    watchexec -e ts,tsx,js,jsx,go,py --debounce 250ms --restart --clear -- just test

watch-lint:
    watchexec -e ts,tsx,js,jsx,go,py --debounce 250ms --restart --clear -- just lint
